# mude o followings pra bater com o seu nome no github and nome de repositorio
baseurl: "/vitoriazoche" # o nome do seu repo do github
url: "https://vitoriazoche.github.io" # o url do teu repo

# informações do seu site como titulo, meta data etc.
title: "Vitória Zoche • Portfólio"
description: "My portfolio as UX/UI Designer"

# color theme for links
# theme-color:

# pagina inicial informação
author-name: Vitória Zoche
author-bio: UI designer learning about UX and new programming frameworks